### ISSUE TITLE
Add a not on the default MongoDB connection mechanism

### ISSUE THREAD

**Issue by olivergierke** [spring-guides/gs-accessing-data-mongodb#11]
The guide stays silent on how the repositories or the `MongoTemplate` are actually selecting the database to interact with. Might be just a matter of adding a small note and a link to the [Boot reference docs](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-mongodb) (although they don't seem to be too precise on that particular topic, either.

Original question on StackOverflow: http://stackoverflow.com/questions/28902150/how-do-spring-repositories-know-where-your-database-is-located

**Comment by gregturn** [comment]
I think this section is quite precise => http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-connecting-to-mongodb. Sounds like a good idea to me.

**Comment by olivergierke** [comment]
You're right. I was probably dragged away by the big code snippet.
