### ISSUE TITLE
spring.datasource.data and spring.datasource.schema properties

### ISSUE THREAD

**Issue by whgibbo** [spring-guides/gs-accessing-data-mongodb#12]
Hi,
Is there an equivalent for mongodb:
* spring.datasource.data 
* spring.datasource.schema

Or does it just work ?
As I can't see any examples of how to pre-populate the datasource.

Many thanks.

**Comment by gregturn** [comment]
I'm not aware of any mechanism to pre-load MongoDB. Definitely doesn't apply when it comes to schema settings given MongoDB is schema-less.

To pre-populate, though, you can use an instance of the repository you define from an initializing bean like this => https://github.com/gregturn/spring-a-gram/blob/master/spring-a-gram-backend/src/main/java/com/greglturnquist/springagram/backend/DatabaseLoader.java
